import { NextRequest, NextResponse } from "next/server";
import { getActiveUser } from "@/lib/auth";
import { getTranscript } from "@/lib/transcriptStorage";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  const user = await getActiveUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: { transcriptId?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON." }, { status: 400 });
  }

  if (!body.transcriptId) {
    return NextResponse.json({ error: "transcriptId is required." }, { status: 400 });
  }

  const transcript = await getTranscript(user.userId, body.transcriptId);
  if (!transcript) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }

  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  const date = new Date(transcript.startedAt).toLocaleDateString("en-US", { dateStyle: "long" });
  const duration = `${Math.round(transcript.durationMinutes)} min`;

  let yPos = 750;
  const lines: string[] = [];
  const PAGE_WIDTH = 595;

  function addLine(text: string, size = 10, color = "0 0 0", bold = false) {
    if (yPos < 50) {
      lines.push("endstream\nendobj\n");
      yPos = 750;
    }
    const fontCmd = bold ? "/F2" : "/F1";
    lines.push(`BT ${fontCmd} ${size} Tf ${color} rg 50 ${yPos} Td (${esc(text.slice(0, 120))}) Tj ET`);
    yPos -= size + 4;
  }

  lines.push("stream");
  addLine(`Dhvani — Meeting Transcript`, 18, "0 0.2 0.4", true);
  addLine(`ITU Innovation Hub`, 10, "0.42 0.45 0.5");
  yPos -= 10;
  addLine(transcript.title, 14, "0 0.2 0.4", true);
  addLine(`${date} | ${duration} | ${transcript.entries.length} entries`, 9, "0.42 0.45 0.5");
  yPos -= 10;

  if (transcript.summary) {
    addLine("Summary", 12, "0 0.2 0.4", true);
    for (const sline of transcript.summary.split("\n").slice(0, 30)) {
      if (sline.trim()) addLine(sline.trim().slice(0, 100), 9, "0.22 0.25 0.32");
    }
    yPos -= 8;
  }

  addLine("Transcript", 12, "0 0.2 0.4", true);
  for (const e of transcript.entries.slice(0, 200)) {
    const id = e.stableSpeakerId || e.rawSpeaker;
    const speaker = (id && transcript.speakerNames?.[id]) || e.speaker || "";
    const prefix = speaker ? `${speaker}: ` : "";
    addLine(`[${e.timestamp}] ${prefix}${e.text}`, 8, "0.12 0.16 0.2");
  }
  if (transcript.entries.length > 200) {
    addLine(`... and ${transcript.entries.length - 200} more entries`, 8, "0.42 0.45 0.5");
  }

  yPos -= 20;
  addLine("Generated by Dhvani — ITU Innovation Hub", 7, "0.42 0.45 0.5");
  lines.push("endstream");

  const stream = lines.join("\n");
  const streamLen = Buffer.byteLength(stream, "utf-8");

  const pdf = [
    "%PDF-1.4",
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    `3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >> endobj`,
    `4 0 obj << /Length ${streamLen} >>\n${stream}\nendobj`,
    "5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    "6 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj",
    "xref",
    "0 7",
    "0000000000 65535 f ",
    "trailer << /Size 7 /Root 1 0 R >>",
    "startxref",
    "0",
    "%%EOF",
  ].join("\n");

  return new NextResponse(pdf, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${transcript.title.replace(/[^a-z0-9]+/gi, "-").slice(0, 50)}.pdf"`,
    },
  });
}
