"use client";

import { Mail } from "lucide-react";

type Props = {
  meetingSubject?: string;
  date?: string;
  summary?: string;
  actionItems?: Array<{ task: string; assignee: string; dueDate?: string | null }>;
  shareUrl?: string;
};

export default function EmailTranscript({ meetingSubject, date, summary, actionItems, shareUrl }: Props) {
  const subject = encodeURIComponent(
    meetingSubject
      ? `Meeting Notes: ${meetingSubject} — ${date || ""}`
      : `Meeting Notes — ${date || "Dhvani"}`
  );

  const parts: string[] = [];
  if (summary) {
    parts.push("SUMMARY\n" + summary.replace(/##\s*/g, "").trim());
  }
  if (actionItems && actionItems.length > 0) {
    parts.push(
      "\nACTION ITEMS\n" +
        actionItems
          .map((a) => `- ${a.task} (${a.assignee})${a.dueDate ? ` due ${a.dueDate}` : ""}`)
          .join("\n")
    );
  }
  if (shareUrl) {
    parts.push(`\nFull transcript: ${shareUrl}`);
  }
  parts.push("\n—\nGenerated by Dhvani — ITU Innovation Hub");

  const body = encodeURIComponent(parts.join("\n"));

  return (
    <a
      href={`mailto:?subject=${subject}&body=${body}`}
      target="_blank"
      rel="noopener noreferrer"
      className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold border border-border-gray text-dark-navy rounded-lg hover:bg-light-gray transition-colors"
    >
      <Mail size={12} />
      Email Summary
    </a>
  );
}
