import type { TranscriptEntry } from "./constants";
import type { ActionItem } from "@/components/ActionItems";

export function generateDocxXml(opts: {
  title: string;
  date: string;
  duration: string;
  entries: TranscriptEntry[];
  speakerNames?: Record<string, string>;
  summary?: string;
  actionItems?: ActionItem[];
}): string {
  const { title, date, duration, entries, speakerNames, summary, actionItems } = opts;

  const resolveSpeaker = (e: TranscriptEntry): string =>
    (e.rawSpeaker && speakerNames?.[e.rawSpeaker]) || e.speaker || "";

  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const paragraphs: string[] = [];

  paragraphs.push(`<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:rPr><w:color w:val="003366"/><w:sz w:val="48"/></w:rPr><w:t>${esc(title)}</w:t></w:r></w:p>`);
  paragraphs.push(`<w:p><w:r><w:rPr><w:color w:val="6B7280"/><w:sz w:val="20"/></w:rPr><w:t>${esc(date)} | ${esc(duration)}</w:t></w:r></w:p>`);
  paragraphs.push(`<w:p/>`);

  if (summary) {
    paragraphs.push(`<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:rPr><w:color w:val="003366"/></w:rPr><w:t>Meeting Summary</w:t></w:r></w:p>`);
    for (const line of summary.split("\n")) {
      if (line.trim()) {
        paragraphs.push(`<w:p><w:r><w:t>${esc(line)}</w:t></w:r></w:p>`);
      }
    }
    paragraphs.push(`<w:p/>`);
  }

  if (actionItems && actionItems.length > 0) {
    paragraphs.push(`<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:rPr><w:color w:val="003366"/></w:rPr><w:t>Action Items</w:t></w:r></w:p>`);
    for (const item of actionItems) {
      const check = item.completed ? "[x]" : "[ ]";
      const due = item.dueDate ? ` (due: ${item.dueDate})` : "";
      paragraphs.push(`<w:p><w:r><w:t>${check} ${esc(item.task)} — ${esc(item.assignee)}${esc(due)}</w:t></w:r></w:p>`);
    }
    paragraphs.push(`<w:p/>`);
  }

  paragraphs.push(`<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:rPr><w:color w:val="003366"/></w:rPr><w:t>Transcript</w:t></w:r></w:p>`);
  for (const e of entries) {
    const speaker = resolveSpeaker(e);
    const prefix = speaker ? `${speaker}: ` : "";
    paragraphs.push(`<w:p><w:r><w:rPr><w:color w:val="6B7280"/><w:sz w:val="18"/></w:rPr><w:t>[${esc(e.timestamp)}] </w:t></w:r><w:r><w:rPr><w:b/><w:color w:val="003366"/></w:rPr><w:t>${esc(prefix)}</w:t></w:r><w:r><w:t>${esc(e.text)}</w:t></w:r></w:p>`);
  }

  paragraphs.push(`<w:p/>`);
  paragraphs.push(`<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:color w:val="6B7280"/><w:sz w:val="16"/></w:rPr><w:t>Generated by Dhvani — ITU Innovation Hub</w:t></w:r></w:p>`);

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:body>
${paragraphs.join("\n")}
</w:body>
</w:document>`;
}
